### ISSUE TITLE
SRL Build - EMF NoClassDefFoundError

### ISSUE THREAD

**Issue by nbachman** [SemanticApplicationDesignLanguage/sadl#401]
@kittaakos 
Attempting to build (mvn install) the SRL project and encountered the following exception: 
INFO: Registered GenModel 'http://www.ge.com/research/sadl/requirements/Requirements' from 'platform:/resource/com.ge.research.sadl.requirements/model/generated/Requirements.genmodel'
3499 [org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main()] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - org/eclipse/emf/mwe2/ecore/CvsIdFilteringGeneratorAdapterFactoryDescriptor
java.lang.NoClassDefFoundError: org/eclipse/emf/mwe2/ecore/CvsIdFilteringGeneratorAdapterFactoryDescriptor
        at org.eclipse.xtext.xtext.generator.ecore.EMFGeneratorFragment2.doGenerate(EMFGeneratorFragment2.java:1010)
        at org.eclipse.xtext.xtext.generator.ecore.EMFGeneratorFragment2.generate(EMFGeneratorFragment2.java:469)
        at org.eclipse.xtext.xtext.generator.CompositeGeneratorFragment2.generate(CompositeGeneratorFragment2.java:50)
        at org.eclipse.xtext.xtext.generator.XtextGenerator.invokeInternal(XtextGenerator.java:230)
        at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:132)
        at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.invoke(Mwe2Bridge.java:34)
        at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:212)
        at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.invoke(AbstractCompositeWorkflowComponent.java:37)
        at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:20)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:102)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.eclipse.emf.mwe2.ecore.CvsIdFilteringGeneratorAdapterFactoryDescriptor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 20 more

**Comment by nbachman** [comment]
The project in question would be the "com.ge.research.sadl.requirements" project. The pom.xml file refers to org.eclipse.emf 2.11.0.

**Comment by kittaakos** [comment]
@nbachman, the [repository](https://github.com/GEGlobalResearch/requirements/) I have access to, has not been updated since Oct 25, 2017. This is on the default, [`master`](https://github.com/GEGlobalResearch/requirements/tree/master) branch. Please update the repo, ping me, and I can fix your build. Thank you!

**Comment by nbachman** [comment]
@kittaakos I have pushed this code to this branch: https://github.com/GEGlobalResearch/requirements/tree/GH-401. 

Thanks for the quick response. Let me know if you need any further information.

**Comment by kittaakos** [comment]
@nbachman, it's done. You will see the PR in the SRL repo. Please ping me if you have any questions, remarks. Otherwise, please close this GH issue. Thank you!

**Comment by nbachman** [comment]
Everything looks fine. Thanks!
