### ISSUE TITLE
Content assist improvements

### ISSUE THREAD

**Issue by kittaakos** [SemanticApplicationDesignLanguage/sadl#406]
Originally from here: https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/issues/80

@crapo [wrote](https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/issues/80#issuecomment-597094071):
> Here's a start. Suppose that I'm creating a brand new model, either in a .sadl file or a .dialog file. I have entered the following statements.
> `Aircraft is a class. Engine is a class. engine describes `
> With the cursor at the end of the last line, content assist gives the correct answers (Aircraft, Engine) along with the also correct answers of all of the classes in implicit models, all in a single alphabetized list. This list also includes all of the primitive data types, e.g., "double", but a primitive datatype cannot be a domain of any property so they should not be included here. (They can ony be ranges, so if the cursor were at the end of `engine describes Aircraft with values of type ` then the primitive datatypes should be included.
> I'm wondering how hard it would be to a) use a SADL preference to include or not include implicit model concepts in content assist, and/or b) list the concepts in this model and any explicitly imported models in an alphabetized list followed by all of the implicit model concepts in a second alphabetized list.

**Comment by crapo** [comment]
`Artefact is a class.`
`Aircraft is `
With cursor at end of 2nd line, there is no content assist available. Why isn't "a" there?

**Comment by kittaakos** [comment]
> `Artefact is a class.`
> `Aircraft is `
> With cursor at end of 2nd line, there is no content assist available. Why isn't "a" there?

Here is a simplified version
```java
Foo is <|>
```

**Comment by kittaakos** [comment]
> Why isn't "a" there?

```
!ENTRY org.eclipse.jface.text 4 0 2020-03-11 13:47:18.939
!MESSAGE Error computing completion proposals.
!STACK 0
java.lang.ClassCastException: com.ge.research.sadl.sADL.impl.SadlClassOrPropertyDeclarationImpl cannot be cast to com.ge.research.sadl.sADL.SadlInstance
	at com.ge.research.sadl.ide.editor.contentassist.SadlOntologyContextProvider.getOntologyContext(SadlOntologyContextProvider.java:142)
	at com.ge.research.sadl.ide.editor.contentassist.ProposalProviderFilterProvider.getCrossReferenceFilter(ProposalProviderFilterProvider.java:91)
	at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider.lambda$4(SadlIdeContentProposalProvider.java:507)
	at org.eclipse.xtext.ide.editor.contentassist.IdeCrossrefProposalProvider.lookupCrossReference(IdeCrossrefProposalProvider.java:58)
	at org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider._createProposals(IdeContentProposalProvider.java:179)
	at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider.createProposals(SadlIdeContentProposalProvider.java:829)
	at org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider._createProposals(IdeContentProposalProvider.java:110)
	at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider._createProposals(SadlIdeContentProposalProvider.java:162)
	at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider.createProposals(SadlIdeContentProposalProvider.java:826)
	at org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider.createProposals(IdeContentProposalProvider.java:94)
	at org.eclipse.xtext.ui.editor.contentassist.UiToIdeContentProposalProvider.createProposals(UiToIdeContentProposalProvider.java:79)
	at com.ge.research.sadl.ui.contentassist.SADLProposalProvider.createProposals(SADLProposalProvider.java:36)
	at org.eclipse.xtext.ui.editor.contentassist.CompletionProposalComputer.exec(CompletionProposalComputer.java:52)
	at org.eclipse.xtext.ui.editor.contentassist.CompletionProposalComputer.exec(CompletionProposalComputer.java:1)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:524)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.priorityReadOnly(XtextDocument.java:488)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.priorityReadOnly(XtextDocument.java:144)
	at org.eclipse.xtext.ui.editor.contentassist.XtextContentAssistProcessor.computeCompletionProposals(XtextContentAssistProcessor.java:76)
	at org.eclipse.jface.text.contentassist.ContentAssistant$2.lambda$0(ContentAssistant.java:2014)
	at java.util.Collections$SingletonSet.forEach(Collections.java:4767)
	at org.eclipse.jface.text.contentassist.ContentAssistant$2.run(ContentAssistant.java:2013)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:2010)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:573)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.lambda$0(CompletionProposalPopup.java:503)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:498)
	at org.eclipse.jface.text.contentassist.ContentAssistant.showPossibleCompletions(ContentAssistant.java:1824)
	at org.eclipse.jface.text.source.SourceViewer.doOperation(SourceViewer.java:978)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.doOperation(ProjectionViewer.java:1461)
	at org.eclipse.ui.texteditor.ContentAssistAction.lambda$0(ContentAssistAction.java:85)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.texteditor.ContentAssistAction.run(ContentAssistAction.java:84)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:121)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:584)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:653)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:443)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$2(KeyBindingDispatcher.java:386)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1113)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4314)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1549)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Canvas.sendKeyEvent(Canvas.java:521)
	at org.eclipse.swt.widgets.Control.doCommandBySelector(Control.java:1094)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6161)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSResponder.interpretKeyEvents(NSResponder.java:71)
	at org.eclipse.swt.widgets.Composite.keyDown(Composite.java:604)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5993)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:235)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2158)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2414)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6113)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5352)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5504)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:131)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3757)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
```

**Comment by crapo** [comment]
Continuing above, 
`Artefact is a class.`
`part describes Artefact with values of type Artefact.`
`Aircraft is a type of Artefact.`
`Engine is a type of Artefact.`
With cursor on new line below last statement, content assist is missing "part". Since statements can begin with a property, it should be. (e.g., 
`part of Aircraft has at least one value of type Engine.`

Also, if cursor is at end of `part of Aircraft has at least ` there is a failure to provide content assist.

**Comment by crapo** [comment]
Having the ontology above, if I type
`MyAircraft is an Aircraft `
and then ask for content assist, "with" is in the list. But, if I type "w" and then ask for content assist, shouldn't only items starting with "w" be included?

**Comment by crapo** [comment]
This is not content assist, but I'm going to put it here. Having defined concepts as above, I type
`part of Engine has at least one value of type Compressor.` 
where Compressor is not defined. Now if I mouse over "Compressor" and select "Create class definition" as a quick fix: a) if I'm at the end of the line and it is also the end of the file, nothing happens in the window, or b) if there is a newline then "Shape is " is inserted and the cursor is moved to the beginning of "Compressor". How hard would it be to insert "Compressor is " (that's what used to happen long ago) and move the cursor to the end of the new partial statement?

**Comment by kittaakos** [comment]
> `Artefact is a class.`
> `Aircraft is `
> With cursor at end of 2nd line, there is no content assist available. Why isn't "a" there?

:+1: Fixed.

**Comment by kittaakos** [comment]
> Continuing above,
> `Artefact is a class.`
> `part describes Artefact with values of type Artefact.`
> `Aircraft is a type of Artefact.`
> `Engine is a type of Artefact.`
> With cursor on new line below last statement, content assist is missing "part". Since statements can begin with a property, it should be. (e.g.,
> `part of Aircraft has at least one value of type Engine.`
> 
> Also, if cursor is at end of `part of Aircraft has at least ` there is a failure to provide content assist.

@crapo did you mean this?
```java
uri "http://sadl.org/x.sadl".
Artefact is a class.
part describes Artefact with values of type Artefact.
Aircraft is a type of Artefact.
Engine is a type of Artefact.
<|> // <-- why cannot you see `part` here?
```

Update: `part` is not a keyword but a SADL resource. Do you want to allow all SADL resources from the scope to be proposed besides the valid keywords?

**Comment by crapo** [comment]
Yes, sorry. The stuff after was just to show an example of a line starting with "part".

**Comment by kittaakos** [comment]
`part` is not a keyword but a SADL resource. Do you want to allow all SADL resources from the scope to be proposed besides the valid keywords?

**Comment by crapo** [comment]
humm... There are statements that can start with SadlResource. I guess this is similar to the previous question about whether the implicit model concepts, if to be included, can be a second sublist. Is it possible to display the keywords first, followed by an alphabetized list of SadlResources? The keywords are much more likely to be what is wanted, so it would be a shame to bury them in a long list. But if one is actually looking for a SadlResource it would be a shame if it weren't there....

**Comment by kittaakos** [comment]
> I guess back to a previous question. Is it possible to display the keywords first, followed by an alphabetized list of SadlResources?

Yes. Thank you for the clarification. Consider it done 👍

**Comment by kittaakos** [comment]
> Continuing above,
> `Artefact is a class.`
> `part describes Artefact with values of type Artefact.`
> `Aircraft is a type of Artefact.`
> `Engine is a type of Artefact.`
> With cursor on new line below last statement, content assist is missing "part". Since statements can begin with a property, it should be. (e.g.,
> `part of Aircraft has at least one value of type Engine.`

Done 👍

**Comment by kittaakos** [comment]
> Also, if cursor is at end of `part of Aircraft has at least ` there is a failure to provide content assist.

After `at least` comes a `CardinalityValue` which is neither a cross-reference nor a keyword? What do you expect? Shall we propose:
```
one
2
3
4
4
5
6
7
etc.
```
?

Otherwise, it won't fix.

**Comment by kittaakos** [comment]
> After `at least` comes a `CardinalityValue` which is neither a cross-reference nor a keyword? What do you expect? Shall we propose:

In action:

![screencast 2020-03-12 10-36-51](https://user-images.githubusercontent.com/1405703/76507764-9eefda80-644d-11ea-85ee-aae73abaf303.gif)

**Comment by kittaakos** [comment]
> Also, if cursor is at end of `part of Aircraft has at least ` there is a failure to provide content assist.

Done 👍

**Comment by kittaakos** [comment]
> This is not content assist,

Moved to #409

**Comment by kittaakos** [comment]
> Having the ontology above, if I type
> `MyAircraft is an Aircraft `
> and then ask for content assist, "with" is in the list. But, if I type "w" and then ask for content assist, shouldn't only items starting with "w" be included?

It is done 👍

**Comment by crapo** [comment]
Create a new model.
Add line "area is a property with values of type float."
Add a line "Shape is a class described by "
With cursor at the end of this line, ask for content assist; none is available.
Arguably "area" should be on the list as adding "area" to this statement would be a reasonable thing to do and would put "Shape" in its domain.
The filter would be properties that do not have "Shape" or any of its super classes in its domain.
If this is just an ontology query issue, I can handle it if you would please point me to where the fix would go.

**Comment by kittaakos** [comment]
> Create a new model.
> Add line "area is a property with values of type float."
> Add a line "Shape is a class described by "
> With cursor at the end of this line, ask for content assist; none is available.
> Arguably "area" should be on the list as adding "area" to this statement would be a reasonable thing to do and would put "Shape" in its domain.
> The filter would be properties that do not have "Shape" or any of its super classes in its domain.
> If this is just an ontology query issue, I can handle it if you would please point me to where the fix would go.

Moved to https://github.com/crapo/sadlos2/issues/412.
