### ISSUE TITLE
NPE from the SADL model processor when working on broken AST

### ISSUE THREAD

**Issue by kittaakos** [SemanticApplicationDesignLanguage/sadl#408]
I got this when I wanted to finetune the content assist. Originally from [here](https://github.com/crapo/sadlos2/issues/406#issuecomment-597614539):

`MyModel.sadl`:
```
uri "http://sadl.org/x.sadl".
Artefact is a class.
part describes Artefact with values of type Artefact.
Aircraft is a type of Artefact.
Engine is a type of Artefact.
part of Aircraft has at least<|>
```

Exception:
```
!ENTRY org.eclipse.core.net 1 0 2020-03-11 15:49:34.332
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences
java.lang.NullPointerException
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.sadlConditionToOntClass(JenaBasedSadlModelProcessor.java:11931)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processSadlProperty(JenaBasedSadlModelProcessor.java:8729)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processModelElement(JenaBasedSadlModelProcessor.java:1278)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:1191)
	at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:75)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:71)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:55)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:76)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:57)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:91)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.util.concurrent.WrappingCancelableUnitOfWork.exec(WrappingCancelableUnitOfWork.java:57)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:524)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:496)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:135)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:49)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:86)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by crapo** [comment]
Fixed in my local copy. You can add this (line #'s different)
![image](https://user-images.githubusercontent.com/1186278/76433489-c92c9400-638a-11ea-9b2c-e25f103396c1.png)
