### ISSUE TITLE
Adjust quick fix provider for SADL resource creation

### ISSUE THREAD

**Issue by kittaakos** [SemanticApplicationDesignLanguage/sadl#409]
@crapo [wrote](https://github.com/crapo/sadlos2/issues/406#issuecomment-597630739):
> This is not content assist, but I'm going to put it here. Having defined concepts as above, I type
> `part of Engine has at least one value of type Compressor.`
> where Compressor is not defined. Now if I mouse over "Compressor" and select "Create class definition" as a quick fix: a) if I'm at the end of the line and it is also the end of the file, nothing happens in the window, or b) if there is a newline then "Shape is " is inserted and the cursor is moved to the beginning of "Compressor". How hard would it be to insert "Compressor is " (that's what used to happen long ago) and move the cursor to the end of the new partial statement?

**Comment by kittaakos** [comment]
> a) if I'm at the end of the line and it is also the end of the file, nothing happens in the window

```
!ENTRY org.eclipse.core.net 1 0 2020-03-12 14:23:21.977
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences

!ENTRY org.eclipse.ui 4 0 2020-03-12 14:24:23.578
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.emf.common.util.WrappedException: java.lang.RuntimeException: org.eclipse.jface.text.BadLocationException
	at org.eclipse.xtext.ui.editor.quickfix.IssueResolution.apply(IssueResolution.java:78)
	at org.eclipse.xtext.ui.editor.quickfix.QuickAssistCompletionProposal.apply(QuickAssistCompletionProposal.java:36)
	at org.eclipse.xtext.ui.editor.hover.AnnotationWithQuickFixesHover$AnnotationInformationControl.apply(AnnotationWithQuickFixesHover.java:536)
	at org.eclipse.xtext.ui.editor.hover.AnnotationWithQuickFixesHover$AnnotationInformationControl.access$2(AnnotationWithQuickFixesHover.java:513)
	at org.eclipse.xtext.ui.editor.hover.AnnotationWithQuickFixesHover$AnnotationInformationControl$5.widgetSelected(AnnotationWithQuickFixesHover.java:507)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4319)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1585)
	at org.eclipse.swt.widgets.Link.textView_clickOnLink_atIndex(Link.java:799)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6535)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:235)
	at org.eclipse.swt.widgets.Widget.mouseDownSuper(Widget.java:1146)
	at org.eclipse.swt.widgets.Widget.mouseDown(Widget.java:1138)
	at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2622)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5989)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:235)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2158)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2414)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6113)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5352)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5504)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:131)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3757)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: java.lang.RuntimeException: org.eclipse.jface.text.BadLocationException
	at org.eclipse.xtext.ui.editor.model.edit.ReconcilingUnitOfWork.exec(ReconcilingUnitOfWork.java:69)
	at org.eclipse.xtext.ui.editor.model.edit.ReconcilingUnitOfWork.exec(ReconcilingUnitOfWork.java:1)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:431)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:164)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.modify(XtextDocument.java:157)
	at org.eclipse.xtext.ui.editor.model.edit.SemanticModificationWrapper.apply(SemanticModificationWrapper.java:32)
	at org.eclipse.xtext.ui.editor.quickfix.IssueResolution.apply(IssueResolution.java:76)
	... 51 more
Caused by: org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.AbstractDocument.getChar(AbstractDocument.java:782)
	at com.ge.research.sadl.ui.quickfix.SADLQuickfixProvider.lambda$8(SADLQuickfixProvider.java:226)
	at org.eclipse.xtext.ui.editor.model.edit.SemanticModificationWrapper$1.process(SemanticModificationWrapper.java:36)
	at org.eclipse.xtext.ui.editor.model.edit.SemanticModificationWrapper$1.process(SemanticModificationWrapper.java:1)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
	at org.eclipse.xtext.ui.editor.model.edit.ReconcilingUnitOfWork.exec(ReconcilingUnitOfWork.java:56)
	... 58 more

```

**Comment by kittaakos** [comment]
> "Shape is "

@crapo, why do we have a hard-coded `Shape is` in the quick fixes? Can you please describe what was the intention here?

https://github.com/crapo/sadlos2/blob/8ffd3c0a9d06af604227e416afdf05ad05c3ea46/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/quickfix/SADLQuickfixProvider.xtend#L142-L151

I am happy to adjust the quick fix provider for missing SADL resurces if you can describe how it should work.

**Comment by kittaakos** [comment]
In action:
![screencast 2020-04-22 15-31-53](https://user-images.githubusercontent.com/1405703/79990203-0cf9d980-84b1-11ea-9f13-8626bc621c0c.gif)

The changeset is part of https://github.com/crapo/sadlos2/pull/416.
