### ISSUE TITLE
IAE in scope provider when working with a broken AST

### ISSUE THREAD

**Issue by kittaakos** [SemanticApplicationDesignLanguage/sadl#430]
`base.sadl`:
```java
 uri "http://sadl.org/base.sadl".
 Base is a class.
```

`sub.sadl`:
```java
 uri "http://sadl.org/sub.sadl".
 import "http://sadl.org/base.sadl" as base.
 
 MySub is a Base.
 MySub is a base:Base.
 base:Base is a class.
```

```
21   [Worker-0: Xtext validation] ERROR org.eclipse.xtext.ui.editor.validation.ValidationJob  - Error running validator
org.eclipse.emf.common.util.WrappedException: java.lang.IllegalArgumentException: prefix must not be null
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:245)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doResolveLazyCrossReference(LazyLinkingResource.java:204)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.resolveLazyCrossReference(LazyLinkingResource.java:163)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.resolveLazyCrossReferences(LazyLinkingResource.java:149)
	at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:505)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.resolveProxies(ResourceValidatorImpl.java:162)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:75)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:55)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:57)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:92)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.util.concurrent.WrappingCancelableUnitOfWork.exec(WrappingCancelableUnitOfWork.java:58)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:92)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:525)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:497)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:136)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:50)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:87)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:68)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalArgumentException: prefix must not be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at org.eclipse.xtext.naming.QualifiedName.startsWith(QualifiedName.java:492)
	at org.eclipse.xtext.naming.QualifiedName.startsWith(QualifiedName.java:484)
	at com.ge.research.sadl.scoping.SADLScopeProvider.handleSadlResource(SADLScopeProvider.java:800)
	at com.ge.research.sadl.scoping.SADLScopeProvider.internalGetLocalResourceScope(SADLScopeProvider.java:671)
	at com.ge.research.sadl.scoping.SADLScopeProvider.lambda$0(SADLScopeProvider.java:316)
	at com.ge.research.sadl.scoping.SADLScopeProvider$3.getLocalScope(SADLScopeProvider.java:1002)
	at com.ge.research.sadl.scoping.SADLScopeProvider.lambda$22(SADLScopeProvider.java:623)
	at com.ge.research.sadl.scoping.SADLScopeProvider$2.get(SADLScopeProvider.java:631)
	at com.ge.research.sadl.scoping.SADLScopeProvider$2.get(SADLScopeProvider.java:1)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at com.ge.research.sadl.scoping.SADLScopeProvider.createResourceScope(SADLScopeProvider.java:635)
	at com.ge.research.sadl.scoping.SADLScopeProvider.createResourceScope(SADLScopeProvider.java:580)
	at com.ge.research.sadl.scoping.SADLScopeProvider.getSadlResourceScope(SADLScopeProvider.java:389)
	at com.ge.research.sadl.scoping.SADLScopeProvider.getScope(SADLScopeProvider.java:380)
	at org.eclipse.xtext.linking.impl.DefaultLinkingService.getScope(DefaultLinkingService.java:59)
	at com.ge.research.sadl.scoping.ErrorAddingLinkingService.getLinkedObjects(ErrorAddingLinkingService.java:55)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:266)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:237)
	... 22 more

```

**Comment by crapo** [comment]
This can be closed when PR #600 is merged into development.
