### ISSUE TITLE
Test with not test/query/explain (etc.) statements causes unexpected error

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#448]
`Inference of 'C:\sadl\git\sadlos2\sadl3\Examples\SemanticsSeminar\PredicateLogic7.sadl' requested.
Unexpected inference result is not a SadlCommandResult (nulljava.lang.NullPointerException
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.displayInferenceResults(SadlRunInferenceHandler.java:174)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.run(SadlRunInferenceHandler.java:92)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.run(SadlRunInferenceHandler.java:76)
	at com.ge.research.sadl.ui.handlers.RunInference$1$1.run(RunInference.java:74)`

**Comment by crapo** [comment]
Fixed, will be in next release.

**Comment by crapo** [comment]
fixed in today's release
