### ISSUE TITLE
NPE on " Cain has sister (a Woman age )."

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#453]
java.lang.NullPointerException
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.assignInstancePropertyValue(JenaBasedSadlModelProcessor.java:10430)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processSadlInstance(JenaBasedSadlModelProcessor.java:10053)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processModelElement(JenaBasedSadlModelProcessor.java:1311)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:1244)
	at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:75)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:71)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:91)

**Comment by crapo** [comment]
fixed in next release.
