### ISSUE TITLE
NullPointerException in ModelCom.add, in JenaBasedSadlModelProcessor.processSadlDifferentFrom

### ISSUE THREAD

**Issue by Ptival** [SemanticApplicationDesignLanguage/sadl#466]
Sorry for all the tickets!

Whenever I save a SADL file, some time through the processing (I do get OWL files generated), the following exception is raised:

```
java.lang.NullPointerException
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.add(ModelCom.java:1148)
	at com.hp.hpl.jena.rdf.model.impl.ResourceImpl.addProperty(ResourceImpl.java:277)
	at com.hp.hpl.jena.rdf.model.impl.RDFListImpl.newListCell(RDFListImpl.java:976)
	at com.hp.hpl.jena.rdf.model.impl.RDFListImpl.with(RDFListImpl.java:375)
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.createList(ModelCom.java:862)
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.createList(ModelCom.java:874)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processSadlDifferentFrom(JenaBasedSadlModelProcessor.java:9801)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processModelElement(JenaBasedSadlModelProcessor.java:1309)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:1244)
	at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:75)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:71)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:91)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:55)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:57)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:92)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.util.concurrent.WrappingCancelableUnitOfWork.exec(WrappingCancelableUnitOfWork.java:58)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:70)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:525)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:497)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:136)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:50)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:87)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:68)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

The issue seems to arise from this call:

https://github.com/crapo/sadlos2/blob/a8d34102e1940212fde0ebdc86eb4a4db2b84ffa/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java#L9801

I'm using the 3.3.0.20200527 update.

**Comment by crapo** [comment]
Can you please provide me with a minimal .sadl file that produces this error? Presumably you have a different from construct of some kind in the model.

**Comment by Ptival** [comment]
Figured it out, it happens on this minimal example:

```
uri "http://sadl.org/Minimal" alias Minimal.

Entity is a class.

CodeFile is an Entity.

{CodeFile, SomeModel} are not the same.

SomeModel is an Entity.
```

It is solved by moving the declaration of `SomeModel` as an `Entity` above the `are not the same` line that mentions it.

**Comment by crapo** [comment]
Thank you for the excellent example. The order should not matter. This is fixed and will be in the next release.
