### ISSUE TITLE
RuntimeException org.eclipse.jface.viewers.ColumnViewer.checkBusy(ColumnViewer.java:764)

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#488]
@kittaakos , this has appeared recently and I'm not sure why. Here's the stack trace:
`java.lang.RuntimeException
	at org.eclipse.jface.viewers.ColumnViewer.checkBusy(ColumnViewer.java:764)
	at org.eclipse.jface.viewers.ColumnViewer.update(ColumnViewer.java:543)
	at org.eclipse.ui.navigator.CommonViewer.update(CommonViewer.java:515)
	at org.eclipse.jface.viewers.StructuredViewer.update(StructuredViewer.java:1976)
	at org.eclipse.ui.internal.navigator.resources.nested.NestedProjectsLabelProvider.lambda$2(NestedProjectsLabelProvider.java:87)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)`

If I set a bkpt at NestedProjectsLabelProvider line 87 then I get two processes stopped at that location.

**Comment by kittaakos** [comment]
> appeared recently

It's not a new issue: https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/issues/122#issue-612727417
