### ISSUE TITLE
Can we import types using the CSV Importer ?

### ISSUE THREAD

**Issue by amarbanerjee23** [SemanticApplicationDesignLanguage/sadl#502]
Hi again,

Sorry, if I am creating to many issues, but I am really liking the SADL and would like to know all possible strengths of the language.
This time, I want to import a csv file. I am creating the following import specification in tmpl file:-

```
import "http://sadl.org/Class1.sadl".

<D> is a type of Class1  .
<A> is a <D>  .
<A> has nodeName <B> .
<A> has description <B> .
```

The error stack is below:-

```
Throwable in doImport: Triple predicate 'is' isn't valid.
com.ge.research.sadl.reasoner.ConfigurationException: Triple predicate 'is' isn't valid.
	at com.ge.research.sadl.jena.importer.CsvImporter.useTemplateProperty(CsvImporter.java:2851)
	at com.ge.research.sadl.jena.importer.CsvImporter.processGroup(CsvImporter.java:2383)
	at com.ge.research.sadl.jena.importer.CsvImporter.doImport(CsvImporter.java:2187)
	at com.ge.research.sadl.jena.importer.CsvImporter.getOwlModel(CsvImporter.java:2069)
	at com.ge.research.sadl.ui.imports.CsvImportOperation.importFile(CsvImportOperation.java:729)
	at com.ge.research.sadl.ui.imports.CsvImportOperation.importRecursivelyFrom(CsvImportOperation.java:1042)
	at com.ge.research.sadl.ui.imports.CsvImportOperation.importFileSystemObjects(CsvImportOperation.java:934)
	at com.ge.research.sadl.ui.imports.CsvImportOperation.execute(CsvImportOperation.java:497)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:110)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:131)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

I have a csv file which has the different sub-types as well as the instances in the same csv sheet, where
D  is the column of the sub-types (Has repeated types)
A is the column of the instance names
B is the column of the attributes of A

The CSV file is like below:-

```
Instance<A> | NodeName<B> | Description  <C> | Type <D>
A1                 | N1                     | Some Desc         | Class1
A2                 | N2                     | Some Desc         | Class1
A3                 | N3                     | Some Desc         | Class2
A4                 | N4                     | Some Desc         | Class3
A5                 | N5                     | Some Desc         | Class2
```

Please see if you could help in this.

Thanks again,
Cheers,
Amar

**Comment by crapo** [comment]
The template grammar isn't exactly like the sadl grammar. Use "rdf:type" and "rdfs:subClassOf" rather than "is a" and "is a type of".
Put strings in quotes, e.g., 

<A> has nodeName "<B>" .

I'll try to get the documentation out this week. I'm sure some documentation would help :-)

**Comment by amarbanerjee23** [comment]
Thanks Again, Andrew !!

 I hope I haven't been a huge pain in the neck. :D

Cheers,
Amar

**Comment by amarbanerjee23** [comment]
Hi Andrew,

Hope you and your team are well. I am trying to see if we could query the
SADL models from externally.

I wanted to find some API's which could query OWL and produce results as
EMF.

E.g. getInstancesofClass(ClassX) returns EList<SadlResource>. Does the
current code base support such APIs ?

Here the ClassX is an SADL Class and the expected outcome is a list of
SadlResources which are instances of ClassX.
Could you please point me towards such a module ?

Stay Safe,

Cheers,
Amar
