### ISSUE TITLE
SADL 3.4.0 failing out of the box NoClassDefFoundError

### ISSUE THREAD

**Issue by Ptival** [SemanticApplicationDesignLanguage/sadl#507]
On a fresh installation of Eclipse 2020-03 and the SADL 3.4.0 Eclipse plug-in, creating an empty project with one SADL file:

```
uri "http://arcos.rack/DEBUG-SADL" alias DEBUG_SADL.
```

It generates the OWL files, but in the console, I get the following exception:

```
java.lang.NoClassDefFoundError: javax/activation/DataSource
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.newInstance(Class.java:556)
	at com.ge.research.sadl.builder.ConfigurationManagerForIDE.getClassInstance(ConfigurationManagerForIDE.java:586)
	at com.ge.research.sadl.reasoner.ConfigurationManager.getReasonerInstance(ConfigurationManager.java:612)
	at com.ge.research.sadl.reasoner.ConfigurationManager.getTranslatorInstance(ConfigurationManager.java:536)
	at com.ge.research.sadl.reasoner.ConfigurationManager.initializeTranslator(ConfigurationManager.java:519)
	at com.ge.research.sadl.reasoner.ConfigurationManager.getTranslator(ConfigurationManager.java:346)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.createBuiltinFunctionImplicitModel(JenaBasedSadlModelProcessor.java:13254)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.checkImplicitBuiltinFunctionModelExistence(JenaBasedSadlModelProcessor.java:1541)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.addImplicitBuiltinFunctionModelImportToJenaModel(JenaBasedSadlModelProcessor.java:1451)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:1169)
	at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:75)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:71)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:91)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:55)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:57)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:92)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.util.concurrent.WrappingCancelableUnitOfWork.exec(WrappingCancelableUnitOfWork.java:58)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:92)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:525)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:497)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:136)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:50)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:87)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:68)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource cannot be found by com.ge.research.sadl.jena-wrapper-for-sadl_3.4.0.202008131540
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 32 more
com.ge.research.sadl.reasoner.ConfigurationException: Unable to instantiate Reasoner 'com.ge.research.sadl.jena.reasoner.JenaReasonerPlugin'
	at com.ge.research.sadl.reasoner.ConfigurationManager.getReasonerInstance(ConfigurationManager.java:627)
	at com.ge.research.sadl.reasoner.ConfigurationManager.getTranslatorInstance(ConfigurationManager.java:536)
	at com.ge.research.sadl.reasoner.ConfigurationManager.initializeTranslator(ConfigurationManager.java:519)
	at com.ge.research.sadl.reasoner.ConfigurationManager.getTranslator(ConfigurationManager.java:346)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.createBuiltinFunctionImplicitModel(JenaBasedSadlModelProcessor.java:13254)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.checkImplicitBuiltinFunctionModelExistence(JenaBasedSadlModelProcessor.java:1541)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.addImplicitBuiltinFunctionModelImportToJenaModel(JenaBasedSadlModelProcessor.java:1451)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:1169)
	at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:75)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:71)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:91)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:55)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:57)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:92)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.util.concurrent.WrappingCancelableUnitOfWork.exec(WrappingCancelableUnitOfWork.java:58)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:92)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:525)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:497)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:136)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:50)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:87)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:68)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Any idea what the problem is?

**Comment by tuxji** [comment]
Valentin, which version of Java are you using?  Oracle unbundled some Java EE APIs like activation in Java 9 and later that had been bundled with Java 8.  I use Java 11 myself and I had been having no problem compiling and running SADL 3.3, but I got some javax.activation.DataSource compilation errors when I tried to build the SADL 3.4 source with Java 11.  

This StackOverflow page (<https://stackoverflow.com/questions/48204141/replacements-for-deprecated-jpms-modules-with-java-ee-apis>) shows what Maven dependencies will add these APIs back, but I found out I still need to do a little more work than that with SADL's manifests and target platform to make the activation API available when I run SADL 3.4 in Eclipse 2020-03 with Java 11.  It will take me some more time to figure out how to make the necessary Java 11 fixes, especially since I'm spread between multiple projects and SADL isn't one of my projects.

In the meantime, you still can run SADL 3.4 with Java 8 if you don't mind switching Java versions.

**Comment by Ptival** [comment]
The above error was using:
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-ga)
OpenJDK 64-Bit Server VM (build 25.222-bga, mixed mode)
```

**Comment by tuxji** [comment]
I've made the necessary changes to fix these activation API problems (both runtime exceptions in Java 8 and compilation/runtime problems in Java 11) and sent @crapo a pull request (#508).  Andy, if my PR passes all checks, you can merge it and close this bug when it is merged.

**Comment by crapo** [comment]
Tests pass, merged.
