### ISSUE TITLE
PropertyWithoutRangeException in console

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#524]
When preferences for type checking are set to require property ranges, and a property doesn't have a range, the following exception ends up in the console window in red. It should be a marker in the editor window.
`com.ge.research.sadl.jena.PropertyWithoutRangeException: Property does not have a range
	at com.ge.research.sadl.jena.JenaBasedSadlModelValidator.getType(JenaBasedSadlModelValidator.java:3314)
	at com.ge.research.sadl.jena.JenaBasedSadlModelValidator.getType(JenaBasedSadlModelValidator.java:3235)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:8133)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:7548)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:4241)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:7733)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:4245)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:4549)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:4233)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processBinaryExpressionByParts(JenaBasedSadlModelProcessor.java:5246)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:4839)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:4233)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processBinaryExpressionByParts(JenaBasedSadlModelProcessor.java:5238)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:4839)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:4233)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processBinaryExpressionByParts(JenaBasedSadlModelProcessor.java:5238)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:4839)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:4233)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processStatement(JenaBasedSadlModelProcessor.java:4114)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processModelElement(JenaBasedSadlModelProcessor.java:1357)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:1284)
	at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:75)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:71)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:91)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:55)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:57)
	at com.ge.research.sadl.ide.handlers.SadlIdeActionHandler.prepareResource(SadlIdeActionHandler.java:88)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.run(SadlRunInferenceHandler.java:106)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.run(SadlRunInferenceHandler.java:77)
	at com.ge.research.sadl.ui.handlers.RunInference$1$1.run(RunInference.java:74)`

**Comment by crapo** [comment]
sometimes the error or warning is placed on the declaration, even though the model element being processed might be in another structure, e.g., a Rule. This would be very difficult to sort out and would likely introduce errors. So for now, error/warning comes out somewhere--OK.
