### ISSUE TITLE
Not able to import a OWL file in SADL file.

### ISSUE THREAD

**Issue by amarbanerjee23** [SemanticApplicationDesignLanguage/sadl#538]
Hi Team,
I am trying out the following. I have an external OWL file and I wish to import it in the SADL description using the  
**import "http://sadl.org/custommodel.owl" as custommodel.**

But I still get error on the import statement as `Couldn't resolve reference to SadlModel 'http://sadl.org/custommodel.owl.` I am following this link [](http://sadl.sourceforge.net/ImportingOWLintoSADL.html)[]

Can anyone please help me out ??

**Comment by crapo** [comment]
The external OWL model needs to have content that identifies the URI of that model, the URI appearing in the import statement. In RDF/XML syntax, this would normally be like this:
`xml:base="http://www.isi.edu/~pan/damltime/time-entry.owl#"`
In N3 sytnax it would be the "@base" statement.
If the OWL model does not have an identifiable URI then the import cannot be resolved.

**Comment by amarbanerjee23** [comment]
No Success yet.
The ont-policy config is 

`  <OntologySpec>
    <publicURI rdf:resource="http://brickschema.org/schema/1.1/Brick"/>
    <language rdf:resource="http://www.w3.org/2002/07/owl"/>
    <altURL rdf:resource="file:///home/amar/Documents/Work/Projects/runtime-SADL/Externals/OwlModels/Brick.owl"/>
</OntologySpec>`

Attaching the OWL and SADL file screenshots.
![owl](https://user-images.githubusercontent.com/7767077/96010301-478c6f80-0e5f-11eb-82e4-c8e8b1dd2dd8.png)
![git](https://user-images.githubusercontent.com/7767077/96010310-48bd9c80-0e5f-11eb-805f-c73ab0761210.png)

Any guess what might be going wrong ??

**Comment by crapo** [comment]
I don't see anything wrong with the mapping or the import statement, given the OWL model content. Is there an error on the import statement that it can't resolve the import? (Not just on the "brick:Building".)  I can't tell from the screenshot for sure. Please attach an exported (archive) project with content to produce the error.

**Comment by amarbanerjee23** [comment]
The error is on the import statement. `Couldn't resolve reference to SadlModel`. The error on the brick:Building is because it is not able to import the OWL model.

**Comment by crapo** [comment]
If you will upload an archive export of a minimal case and tell the version of SADL, I will be happy to try to identify the problem.

**Comment by dahvid** [comment]
I have the same issue.  I'm importing the RadLex.owl ontology. It imports fine in both protege and owlready.   I created a project called "TestRadl" and added a file called "TestRadl.sadl".  I then used the SADL Model URL list file wizard.  The first problem is what url to put in to download?  Also why do I need to download, I have the file itself?  The second is that the wizard doesn't update so if you enter a file://path  that is invalid the first time, you can change it, but hitting "download" doesn't do anything.  I put the RaLex.owl file in the project under OwlFiles/. I needed to reboot Eclipse each time I changed the file path. Finally, I did succeed in importing the file by giving it the full path, it placed it under OwlModels with a duplicate of the full path. I think it worked because I needed to correct some minor syntax errors before it would finish.  The TestRadl.sadl file only has two lines.
 uri "http://sadl.org/TestRadl.sadl".
import "http://radlex.org/RID/" as rad.

The errors are:
Couldn't resolve reference "http://radlex.org/RID/"
Mismatched input <EOF> expecting "."

**Comment by crapo** [comment]
Just to clarify, the purpose of the SADL Model URL  List editor and wizard is to identify existing OWL files, local to your filesystem or on the Internet, that you wish to be able to use in your knowledge base. The requested URL will be where the OWL file is actually located, file://... if on the local file system, http://... if on the Internet. When you switch to the Download tab and click Download, the file is copied into the project, but not into the OwlModels folder, which is reserved for OWL models created by SADL. This verifies that the external OWL file actually exists and places a copy where access is ensured. In this process, SADL looks for the unique identifier of this external model, its URI. The URL and URI provide a mapping, so that when an import statement, whether in a .sadl file or an OWL file, references this model by this URI, SADL can look up the URL of where the file can be found. This will be the URL of the copy, not the original URL which was copied. If a URI isn't found for the OWL mode a mapping cannot be made and import will not be possible.

Now, with respect to the 'import "http://radlex.org/RID/" as rad.' statement, I downloaded RadLex.owl from [https://drive.google.com/file/d/1U3GnoceTDk7XBhmrjVIMUtW1miXHG6Wl/view?usp=drive_web](https://drive.google.com/file/d/1U3GnoceTDk7XBhmrjVIMUtW1miXHG6Wl/view?usp=drive_web) and took a look. I observe:
1. There is no "xml:base=..." tab in the opening <rdf:RDF> tag.
2. On line 1,277,292 there is an owl:Ontology definition: 
`<rdf:Description rdf:about="http://radlex.org/ont/radlex.owl">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Ontology"/>
	<owl:imports rdf:resource="http://radlex.org/ont/radlex.owl"/>
</rdf:Description>`
This appears to indicate that the ontology imports itself. Not sure what that means. This is the only owl:Ontology definition in the file but isn't what you're using in the import statement and isn't used as xml:base. 

In any case, I tried to use the wizard to bring the OWL file into the SADL project. I got this error:
`[Fatal Error] :11767:273: Invalid byte 3 of 3-byte UTF-8 sequence.
org.xml.sax.SAXParseException; lineNumber: 11767; columnNumber: 273; Invalid byte 3 of 3-byte UTF-8 sequence.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at com.ge.research.sadl.external.XMLHelper._tryReadBaseUri(XMLHelper.java:147)
...`
suggesting that there are characters in the file that the Xerces parser isn't handling. This error occurs while SADL is looking for a URI to use, but it must also be parsable for the OWL file to be indexed by Xtext for hyperlinnking. If the file can't be "downloaded" by the wizard it will not be available for import into a SADL model.

**Comment by crapo** [comment]
I went a little further and replaced all of the unparsable chars in the RadLex.owl file and then it was able to be "downloaded". Then I looked in the mapping file where I observed that it found "http://radlex.org/RID/" as the URI of the external model. Creating a .sadl file and adding the statement
`import "http://radlex.org/RID/".`
I then got this error on that statement:
`Unable to import indirect import with URI 'http://radlex.org/RID/'`
caused, I think, by the import of itself discussed above.

**Comment by dahvid** [comment]
Hi Andy,
I fixed the parsing error in my version, there are extra blank characters
that are not being parsed, the RadLex.owl file I sent you parses OK.  But I
didn't know that about the OwlModels directory. I'll try this again and get
back to you.
Regards,
David

**Comment by dahvid** [comment]
OK, I got it too work. The trick was to put the RadLex.owl file outside the project for import. and to fix the non-parsing blank characters in the .owl file.  Since both Protege and owlread parse this file fine you should probably consider the rejection of these blank characters as a bug.

**Comment by amarbanerjee23** [comment]
Which are the non parsing blank characters ??
Can anyone show me an example ?? I have everything correct. The URL approach works for one OWL file but dosent work for another OWL file.

**Comment by dahvid** [comment]
Every place there was a url of the format
"rdf:resource="http://radlex.org/RID/RID1117; RID1095"
I needed to take out the space after the semi-colon

**Comment by crapo** [comment]
@amarbanerjee23 , @dahvid , can this issue be closed? I believe that some of the causes of confusion have been improved in the latest version of SADL.
