### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#554]
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878)
	at com.google.common.base.Optional.of(Optional.java:103)
	at com.ge.research.sadl.ide.editor.contentassist.SadlOntologyContextProvider.getOntologyContext(SadlOntologyContextProvider.java:304)
	at com.ge.research.sadl.ide.editor.contentassist.ProposalProviderFilterProvider.getCrossReferenceFilter(ProposalProviderFilterProvider.java:83)
	at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider.lambda$7(SadlIdeContentProposalProvider.java:591)
	at com.google.common.base.Predicates$AndPredicate.apply(Predicates.java:353)
	at org.eclipse.xtext.ide.editor.contentassist.IdeCrossrefProposalProvider.lookupCrossReference(IdeCrossrefProposalProvider.java:45)
	at org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider._createProposals(IdeContentProposalProvider.java:144)
	at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider.createProposals(SadlIdeContentProposalProvider.java:913)
	at org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider._createProposals(IdeContentProposalProvider.java:88)
	at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider._createProposals(SadlIdeContentProposalProvider.java:177)
	at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider.createProposals(SadlIdeContentProposalProvider.java:910)
	at org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider.createProposals(IdeContentProposalProvider.java:71)
	at com.ge.research.sadl.ui.contentassist.SADLUiToIdeContentProposalProvider.createProposals(SADLUiToIdeContentProposalProvider.java:53)
	at com.ge.research.sadl.ui.contentassist.SADLProposalProvider.createProposals(SADLProposalProvider.java:32)

**Comment by crapo** [comment]
I believe this has long since been OBE.
