### ISSUE TITLE
Quick Start Tutorial creation on GitHub

### ISSUE THREAD

**Issue by BenHocking** [SemanticApplicationDesignLanguage/sadl#605]
The Quick Start Tutorial at the SourceForge location is almost, but not quite, compatible with this GitHub version. The two issues I encounter are:

1. The line `GeorgeWashington is the same as George.` yields an "Unknown" error message.
2. When trying to test the `Ask: "select ?x where {<George> <rdf:type> ?x}".` line using Jena (using `OWL_MEM_RDFS`), I get the result:
```
Build process completed for 1 project.
Beginning SADL clean process...
SADL clean/build process completed for 1 project in 0 seconds
No currently selected file; can't test model.
com.ge.research.sadl.reasoner.TranslationException: Invalid format: 
	at com.ge.research.sadl.model.SadlSerializationFormat.getRDFFormat(SadlSerializationFormat.java:64)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.run(SadlRunInferenceHandler.java:86)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.run(SadlRunInferenceHandler.java:78)
	at com.ge.research.sadl.ui.handlers.RunInference$1$1.run(RunInference.java:74)
Invalid format: com.ge.research.sadl.reasoner.TranslationException: Invalid format: 
	at com.ge.research.sadl.model.SadlSerializationFormat.getRDFFormat(SadlSerializationFormat.java:64)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.run(SadlRunInferenceHandler.java:86)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.run(SadlRunInferenceHandler.java:78)
	at com.ge.research.sadl.ui.handlers.RunInference$1$1.run(RunInference.java:74)

```

**Comment by crapo** [comment]
I tried to reproduce the errors you describe in the latest release, Version 3.5.0.202012241659, but was unable to do so. If you are using the latest release please export and attach the project producing these errors. Thanks!

**Comment by crapo** [comment]
@BenHocking , is this still an issue? If not, can this please be closed. Thanks.
