### ISSUE TITLE
ClassNotFoundException firstElement

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#649]
I'm getting this error. It seems to be looking for firstElement in the wrong place. 

java.lang.ClassNotFoundException: com.ge.research.sadl.jena.reasoner.builtin.firstElement cannot be found by com.ge.research.sadl.jena-wrapper-for-sadl_3.5.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.ge.research.sadl.jena.reasoner.JenaReasonerPlugin.addBuiltin(JenaReasonerPlugin.java:2467)
	at com.ge.research.sadl.jena.reasoner.JenaReasonerPlugin.configure(JenaReasonerPlugin.java:2523)
	at com.ge.research.sadl.reasoner.ConfigurationManager.applyConfigurationToReasoner(ConfigurationManager.java:685)
	at com.ge.research.sadl.reasoner.ConfigurationManager.initializeReasoner(ConfigurationManager.java:586)
	at com.ge.research.sadl.reasoner.ConfigurationManagerForEditing.initializeReasoner(ConfigurationManagerForEditing.java:344)
	at com.ge.research.sadl.reasoner.ConfigurationManager.getReasoner(ConfigurationManager.java:385)
	at com.ge.research.sadl.jena.JenaBasedSadlInferenceProcessor.getInitializedReasoner(JenaBasedSadlInferenceProcessor.java:1487)
	at com.ge.research.sadl.jena.JenaBasedSadlInferenceProcessor.getReasonerConfigurationItem(JenaBasedSadlInferenceProcessor.java:1916)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.displayInferenceResults(SadlRunInferenceHandler.java:337)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.run(SadlRunInferenceHandler.java:112)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.run(SadlRunInferenceHandler.java:81)
	at com.ge.research.sadl.ui.handlers.RunInference$1$1.run(RunInference.java:74)
java.lang.ClassNotFoundException: com.naturalsemantics.sadl.jena.reasoner.builtin.Length cannot be found by com.ge.research.sadl.jena-wrapper-for-sadl_3.5.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.ge.research.sadl.jena.reasoner.JenaReasonerPlugin.addBuiltin(JenaReasonerPlugin.java:2467)
	at com.ge.research.sadl.jena.reasoner.JenaReasonerPlugin.configure(JenaReasonerPlugin.java:2523)
	at com.ge.research.sadl.reasoner.ConfigurationManager.applyConfigurationToReasoner(ConfigurationManager.java:685)
	at com.ge.research.sadl.reasoner.ConfigurationManager.initializeReasoner(ConfigurationManager.java:586)
	at com.ge.research.sadl.reasoner.ConfigurationManagerForEditing.initializeReasoner(ConfigurationManagerForEditing.java:344)
	at com.ge.research.sadl.reasoner.ConfigurationManager.getReasoner(ConfigurationManager.java:385)
	at com.ge.research.sadl.jena.JenaBasedSadlInferenceProcessor.getInitializedReasoner(JenaBasedSadlInferenceProcessor.java:1487)
	at com.ge.research.sadl.jena.JenaBasedSadlInferenceProcessor.getReasonerConfigurationItem(JenaBasedSadlInferenceProcessor.java:1916)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.displayInferenceResults(SadlRunInferenceHandler.java:337)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.run(SadlRunInferenceHandler.java:112)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.run(SadlRunInferenceHandler.java:81)
	at com.ge.research.sadl.ui.handlers.RunInference$1$1.run(RunInference.java:74)
Derivation information requested but none available.java.lang.ClassNotFoundException: com.ge.research.sadl.jena.reasoner.builtin.firstElement cannot be found by com.ge.research.sadl.jena-wrapper-for-sadl_3.5.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.ge.research.sadl.jena.reasoner.JenaReasonerPlugin.addBuiltin(JenaReasonerPlugin.java:2467)
	at com.ge.research.sadl.jena.reasoner.JenaReasonerPlugin.configure(JenaReasonerPlugin.java:2523)
	at com.ge.research.sadl.reasoner.ConfigurationManager.applyConfigurationToReasoner(ConfigurationManager.java:685)
	at com.ge.research.sadl.reasoner.ConfigurationManager.initializeReasoner(ConfigurationManager.java:586)
	at com.ge.research.sadl.reasoner.ConfigurationManagerForEditing.initializeReasoner(ConfigurationManagerForEditing.java:344)
	at com.ge.research.sadl.reasoner.ConfigurationManager.getReasoner(ConfigurationManager.java:385)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.findOrAddBuiltin(JenaTranslatorPlugin.java:1388)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.builtinTypeToString(JenaTranslatorPlugin.java:1277)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.graphPatternElementToJenaRuleString(JenaTranslatorPlugin.java:933)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.graphPatternElementsToJenaRuleString(JenaTranslatorPlugin.java:391)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.translateRule(JenaTranslatorPlugin.java:256)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.translateAndSaveRules(JenaTranslatorPlugin.java:845)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.translateAndSaveRules(JenaTranslatorPlugin.java:818)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.translateAndSaveModel(JenaTranslatorPlugin.java:172)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.translateAndSaveModel(JenaBasedSadlModelProcessor.java:880)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onGenerate(JenaBasedSadlModelProcessor.java:747)
	at com.ge.research.sadl.generator.ProcessorProviderBasedGenerator.doGenerate(ProcessorProviderBasedGenerator.java:36)
	at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:44)
	at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:35)
	at org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:597)
	at org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:578)
	at org.eclipse.xtext.builder.BuilderParticipant.doGenerate(BuilderParticipant.java:563)
	at org.eclipse.xtext.builder.BuilderParticipant.doBuild(BuilderParticipant.java:303)
	at org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:265)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:164)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:70)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:392)
	at org.eclipse.xtext.builder.impl.XtextBuilder.addInfosFromTaskAndBuild(XtextBuilder.java:322)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:429)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:202)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:845)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:228)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:276)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:329)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:332)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:384)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:405)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
java.lang.ClassNotFoundException: com.naturalsemantics.sadl.jena.reasoner.builtin.Length cannot be found by com.ge.research.sadl.jena-wrapper-for-sadl_3.5.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.ge.research.sadl.jena.reasoner.JenaReasonerPlugin.addBuiltin(JenaReasonerPlugin.java:2467)
	at com.ge.research.sadl.jena.reasoner.JenaReasonerPlugin.configure(JenaReasonerPlugin.java:2523)
	at com.ge.research.sadl.reasoner.ConfigurationManager.applyConfigurationToReasoner(ConfigurationManager.java:685)
	at com.ge.research.sadl.reasoner.ConfigurationManager.initializeReasoner(ConfigurationManager.java:586)
	at com.ge.research.sadl.reasoner.ConfigurationManagerForEditing.initializeReasoner(ConfigurationManagerForEditing.java:344)
	at com.ge.research.sadl.reasoner.ConfigurationManager.getReasoner(ConfigurationManager.java:385)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.findOrAddBuiltin(JenaTranslatorPlugin.java:1388)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.builtinTypeToString(JenaTranslatorPlugin.java:1277)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.graphPatternElementToJenaRuleString(JenaTranslatorPlugin.java:933)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.graphPatternElementsToJenaRuleString(JenaTranslatorPlugin.java:391)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.translateRule(JenaTranslatorPlugin.java:256)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.translateAndSaveRules(JenaTranslatorPlugin.java:845)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.translateAndSaveRules(JenaTranslatorPlugin.java:818)
	at com.ge.research.sadl.jena.translator.JenaTranslatorPlugin.translateAndSaveModel(JenaTranslatorPlugin.java:172)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.translateAndSaveModel(JenaBasedSadlModelProcessor.java:880)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onGenerate(JenaBasedSadlModelProcessor.java:747)
	at com.ge.research.sadl.generator.ProcessorProviderBasedGenerator.doGenerate(ProcessorProviderBasedGenerator.java:36)
	at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:44)
	at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:35)
	at org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:597)
	at org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:578)
	at org.eclipse.xtext.builder.BuilderParticipant.doGenerate(BuilderParticipant.java:563)
	at org.eclipse.xtext.builder.BuilderParticipant.doBuild(BuilderParticipant.java:303)
	at org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:265)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:164)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:70)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:392)
	at org.eclipse.xtext.builder.impl.XtextBuilder.addInfosFromTaskAndBuild(XtextBuilder.java:322)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:429)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:202)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:845)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:228)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:276)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:329)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:332)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:384)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:405)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by agabaldon** [comment]
Now also getting an error about Length not found. Length has been replaced by ListLength.

java.lang.ClassNotFoundException: com.naturalsemantics.sadl.jena.reasoner.builtin.Length cannot be found by com.ge.research.sadl.jena-wrapper-for-sadl_3.5.0.qualifier

**Comment by crapo** [comment]
@agabaldon , the error about Length not being found is expected unless SadlBuiltinFunctions.sadl is deleted and the project is cleaned and rebuilt. The error about FirstElement not being found is inexplicable to me unless someone edited the configuration.rdf file and manually put in "com.ge.research.sadl.jena.reasoner.builtin.firstElement". I don't know how else that would have gotten there.

**Comment by crapo** [comment]
@agabaldon , correction. I know exactly how "com.ge.research.sadl.jena.reasoner.builtin.firstElement" got into the SadlBuiltinFunctions.sadl file. I will fix this shortly.

**Comment by crapo** [comment]
@agabaldon , I think that this issue is long since resolved. Do you believe otherwise?

**Comment by agabaldon** [comment]
Haven't seen that in a while, closing..
