### ISSUE TITLE
how to deploy sadl in webserver

### ISSUE THREAD

**Issue by NAVEENKUMARSKPN** [SemanticApplicationDesignLanguage/sadl#730]
HI Team ,
 
Is it possible to deploy SADL into webserver or not? We would like to know how to expose our sadl to rest api instead of eclipse UI

Thanks

**Comment by crapo** [comment]
@NAVEENKUMARSKPN , interpreting your question to be can you deliver reasoning over and querying a knowledge base via a webserver, the answer is yes. Please see the documentation for [Knowledge as a Service (KaaS)](http://semanticapplicationdesignlanguage.github.io/sadl/KaaS.html), linked from the [Topical Index](http://semanticapplicationdesignlanguage.github.io/sadl/TopicalIndex.html). Currently there is a SOAP Web Service interface which wraps the documented server interface, although I'm not seeing the source code for it on github which perplexes me a bit. @agabaldon , do you know where that code is  found? An incomplete REST interface has been developed and @sanandsasidharan and colleagues were working on that and were supposed to push to the dbimporter branch (see https://github.com/SemanticApplicationDesignLanguage/sadl/issues/548) but it has not happened as far as I know.

**Comment by NAVEENKUMARSKPN** [comment]
Thanks Crapo

**Comment by NAVEENKUMARSKPN** [comment]
Hi Crapo ,

with the KaaS I were trying to import a csv data using loadCsvData method in sadlSeverImpl

I followed the steps mention in Kaas Documents but while executing i am getting malformedUriException

This is how i have did in java spring boot

 ```
ISadlServer srvr = new SadlServerImpl();

 srvr.selectServiceModel("file:\\C:\\Users\\naveen\\runtime-New_configuration\\importDemo\\OwlModels", "http://sadl.org/test.sadl");
 srvr.setKbaseRoot("file:\\C:\\Users\\naveen\\runtime-New_configuration\\importDemo\\OwlModels");
 
 srvr.loadCsvData("E:\\Naveen\\Objects.csv", true,
 				"uri \"http://sadl.org/Objects\".\r\n"
 						+ "import \"http://sadl.org/ObjectTypes.sadl\".\r\n"
 						+ "import \"http://sadl.org/MM.sadl\".\r\n" + "\r\n" + "\r\n" + "<A> rdf:type <D>.\r\n"
 						+ "<A> has nodeName \"<B>\" .\r\n" + "<A> has description \"<C>\" .\r\n"
 						+ "<A> has category \"<E>\" .\r\n" + "<A> has nodeType \"<D>\" .\r\n"
 						+ "<A> has nodeID \"<A>\" .");
```


and this is the exception i got


```
java.net.MalformedURLException: '"http://sadl.org/Objects".' is not a valid URL: no protocol: "http://sadl.org/Objects".
	at com.ge.research.sadl.reasoner.utils.SadlUtils.validateHTTP_URI(SadlUtils.java:94) ~[reasoner-api.jar:?]
	at com.ge.research.sadl.jena.importer.CsvImporter.setImportModelNamespace(CsvImporter.java:1067) ~[classes/:?]
	at com.ge.research.sadl.server.server.SadlServerImpl.loadCsvData(SadlServerImpl.java:226) ~[classes/:?]
	at com.icf.services.main.controller.Importer.importCsvFile(Importer.java:34) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.6.jar:5.3.6]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) ~[tomcat-embed-core-9.0.45.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.45.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.6.jar:5.3.6]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.6.jar:5.3.6]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.6.jar:5.3.6]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```




Did i did any thing wrong in the java?

I have added library  com.ge.research.jena and sadlserverimpl in spring boot...the springboot project also in same workspace

please help me on this



Thanks

**Comment by crapo** [comment]
@NAVEENKUMARSKPN , the problem is the periods after the "uri ..." statement in the template. The template grammar did not originally have periods after statements and while they are ignored  for the body of the template, they aren't in all statements. The error message gives you a clue: MalformedURLException: '"http://sadl.org/Objects".'  So the URL being used is

"http://sadl.org/Objects".

where the double quote is part of the URL, which is not valid. I will fix SadlServer code in the longer term to allow a period after the uri statement.

Note also that "has" in front of predicate name in triple pattern is not valid. See 
[CSV Tabular Data Importer documentation](http://semanticapplicationdesignlanguage.github.io/sadl/CsvDataImporter.html) .

**Comment by NAVEENKUMARSKPN** [comment]
Thanks Crapo !!!
